repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: pretty-format-java
        args: [ --autofix ]
  - repo: https://github.com/eslint/eslint
    rev: v8.21.0
    hooks:
      - id: eslint
        additional_dependencies:
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
