ARG SPLUNK_VERSION=latest
FROM splunk/splunk:$SPLUNK_VERSION
ARG SPLUNK_APP=TA_UNKNOWN
ARG SOURCE_PACKAGE=package

COPY $SOURCE_PACKAGE /opt/splunk/etc/apps/$SPLUNK_APP
COPY test-data/ /opt/splunk/etc/apps/$SPLUNK_APP/data
COPY deps/apps/ /opt/splunk/etc/apps
RUN sudo -u splunk mkdir -p /opt/splunk/etc/users/admin/user-prefs/local
COPY deps/user-prefs.conf /opt/splunk/etc/users/admin/user-prefs/local/user-prefs.conf 
COPY deps/ui-tour.conf /opt/splunk/etc/users/admin/search/local/ui-tour.conf